### ISSUE TITLE
Conflicts with conda environment

### ISSUE THREAD

**Issue by MBadosa** [jeffsonyu/VTacO#2]
Good morning, I am trying to replicate the conda environment from the environment.yaml file, but when i do so, there are conflicts in it, if I wait for the whole process to end it does so, but the environment is not created thus there is no visible error.

Is it possible that the enviornment dependencies is not correctly created?

Thank you in advance!
![image](https://github.com/jeffsonyu/VTacO/assets/115696795/227f1dbb-6198-4801-83c3-1021c26bb999)

**Comment by jeffsonyu** [comment]
Hello! We have updated new methods to create or directly use the environment. Thank you for noticing!
