### ISSUE TITLE
training configs

### ISSUE THREAD

**Issue by Araik-77** [jeffsonyu/VTacO#4]
thanks for your great works

I want to  know how to train a special class, such as "lock", I try to changed classes in VTacO_YCB.YAML, but I get an error as follows:
![2023-06-16 10-45-06屏幕截图](https://github.com/jeffsonyu/VTacO/assets/52837802/ca5b4137-1c0f-41a9-b3e3-ddd2b89edfc2)

**I only changed classes and path**

![2023-06-16 10-45-21屏幕截图](https://github.com/jeffsonyu/VTacO/assets/52837802/1d20e3ab-118c-44ca-948a-26898ed36879)

**Comment by jeffsonyu** [comment]
Hello! For changing the class, you should specify which class you want to train, by changing **path** to: **./data/VTacO_AKB_class/001**. The variable **classes** should be set to null.

**Comment by jeffsonyu** [comment]
Close since no update
