### ISSUE TITLE
'FileNotFoundError' when training the local depth estimator from scratch

### ISSUE THREAD

**Issue by Jeffreyzhaoliang** [jeffsonyu/VTacO#6]
Thanks for your released code and paper. I met a problem when I execute the following command:
```
python train_depth.py configs/tactile/tactile_test.yaml
```
![image](https://github.com/jeffsonyu/VTacO/assets/34564986/3aa0dfbb-f9cb-45b6-971c-186d4f0e7c0f)
Should I touch a empty or a pre-trained model.pt before training?
Have a nice day~

**Comment by jeffsonyu** [comment]
Sorry for the late reply.
The problem can be solved by changing the **FileExistsError** to **FileNotFoundError** in the 137 line of **train.py** file.
We will soon update our code and fix some bugs we have encountered. Thank you for noticing!

**Comment by Jeffreyzhaoliang** [comment]
Thks for your reply, I revise the code as your recommend, and I got the FileNotFoundError.
![image](https://github.com/jeffsonyu/VTacO/assets/34564986/2790b781-daa6-4956-9c68-9d14c2fd9309)

**Comment by jeffsonyu** [comment]
Sorry, you should change the **FileExistsError** to **FileNotFoundError** in **train_depth.py** file.
We have updated our code and you can use the latest version. Thank you!

**Comment by Jeffreyzhaoliang** [comment]
Thks for your update, It works!
