### ISSUE TITLE
 with_contact: False表示什么？

### ISSUE THREAD

**Issue by meiguiz** [jeffsonyu/VTacO#8]
with_contact: False想请问一下这个参数表示什么？是表示使不使用Hand Reconstruction嘛？

**Comment by jeffsonyu** [comment]
Hi! Actually the argument **with_contact** is not needed in our pipeline. It's an argument for testing other method we tried during the training process. Sorry for the rough organization of our code...

**Comment by meiguiz** [comment]
您好！非常抱歉打扰了。我还有一些问题。请问我在现实场景使用VTacO的时候需要的文件有哪些？是不是只需要触觉传感器的位姿参数，触觉图像和RGB-D的相机采集的物体部分点云，我应该把这些参数放在哪里？感谢您的详细回答！

**Comment by jeffsonyu** [comment]
The data you need for inference can be refered to the dataloader we wrote, which can be found in `src/data/core.py`

**Comment by meiguiz** [comment]
您好！打扰了。请问您在论文里的现实世界采集的样例文件可以分享嘛？下图中的样例。万分感谢！
![image](https://github.com/user-attachments/assets/b1bca16f-f8e4-414c-a695-60e01e2772ea)

**Comment by jeffsonyu** [comment]
Sorry for the late reply. Unfortunately, we also lost the original data from that time. You can capture the data through our simulation environment VT-Sim and align real-world data to it.

**Comment by jeffsonyu** [comment]
Close since no update
